spring:
  profiles:
    active: local
server:
  port: 8899
#logging:
#  level:
#    org.springframework: debug
#    org.kafka: debug

---

spring:
  profiles:
    - local
  datasource:
    url: jdbc:postgresql:kafkaone
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      #      naming:
      #        physical-strategy: com.devsubho.backend.utilities.CustomPhysicalNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: 'localhost:29092,localhost:29093,localhost:29094'
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      properties: # overriding defaults
#        acks: all
#        retries: 10
    consumer:
      bootstrap-servers: 'localhost:29092,localhost:29093,localhost:29094'
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    admin:
      properties:
        bootstrap.servers: 'localhost:29092,localhost:29093,localhost:29094'
