version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092,SSL://localhost:9192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #      https://docs.confluent.io/current/kafka/authentication_ssl.html#brokers
      KAFKA_SSL_TRUSTSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/client.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEYSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEY_PASSWORD: ssldemo1
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https # default


  broker2:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9093,PLAINTEXT_HOST://localhost:29093,SSL://localhost:9193
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #      https://docs.confluent.io/current/kafka/authentication_ssl.html#brokers
      KAFKA_SSL_TRUSTSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/client.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEYSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEY_PASSWORD: ssldemo1
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https # default


  broker3:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper
    ports:
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9094,PLAINTEXT_HOST://localhost:29094,SSL://localhost:9194
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #      https://docs.confluent.io/current/kafka/authentication_ssl.html#brokers
      KAFKA_SSL_TRUSTSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/client.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEYSTORE_LOCATION: /Users/somjit.nag/Documents/github/Suedo/Spring/LearningKafka/springbootkafka/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: ssldemo1
      KAFKA_SSL_KEY_PASSWORD: ssldemo1
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https # default

# for a more exhaustive config, refer: https://github.com/confluentinc/cp-all-in-one
